#!/bin/bash
curl 'https://ftp.gnu.org/gnu/readline/readline-8.0.tar.gz' \
    | bsdtar -xpf -
#
mkdir -p -m0755 build/etc/
#
cat - <<INPRC | cat >build/etc/inputrc
# do not bell on tab-completion
#set bell-style none

set meta-flag on
set input-meta on
set convert-meta off
set output-meta on

$if mode=emacs

# for linux console and RH/Debian xterm
"\e[1~": beginning-of-line
"\e[4~": end-of-line
"\e[5~": beginning-of-history
"\e[6~": end-of-history
"\e[7~": beginning-of-line
"\e[3~": delete-char
"\e[2~": quoted-insert
"\e[5C": forward-word
"\e[5D": backward-word
"\e\e[C": forward-word
"\e\e[D": backward-word
"\e[1;5C": forward-word
"\e[1;5D": backward-word

# for rxvt
"\e[8~": end-of-line

# for non RH/Debian xterm, can't hurt for RH/DEbian xterm
"\eOH": beginning-of-line
"\eOF": end-of-line

# for freebsd console
"\e[H": beginning-of-line
"\e[F": end-of-line
$endif
INPRC
#
pushd readline-8.0 2>/dev/zero
# remove RPATH from shared objects (FS#14366)
sed -i 's|-Wl,-rpath,$(libdir) ||g' support/shobj-conf
# fix autreconf bug
while read fix; do
    sed "/^AC_SYS_LARGEFILE\$/ a $fix" -i configure.ac
done <<FIX
AC_DEFINE([CTYPE_NON_ASCII], [], [Description])
AC_DEFINE([FIONREAD_IN_SYS_IOCTL],[],[autoheader-fix])
AC_DEFINE([HAVE_BSD_SIGNALS],[],[autoheader-fix])
AC_DEFINE([HAVE_GETPW_DECLS],[],[autoheader-fix])
AC_DEFINE([HAVE_LANGINFO_CODESET],[],[autoheader-fix])
AC_DEFINE([HAVE_MBRLEN],[],[autoheader-fix])
AC_DEFINE([HAVE_MBSCMP],[],[autoheader-fix])
AC_DEFINE([HAVE_MBSNRTOWCS],[],[autoheader-fix])
AC_DEFINE([HAVE_MBSRTOWCS],[],[autoheader-fix])
AC_DEFINE([HAVE_MBSTATE_T],[],[autoheader-fix])
AC_DEFINE([HAVE_POSIX_SIGNALS],[],[autoheader-fix])
AC_DEFINE([HAVE_POSIX_SIGSETJMP],[],[autoheader-fix])
AC_DEFINE([HAVE_STRUCT_DIRENT_D_FILENO],[],[autoheader-fix])
AC_DEFINE([HAVE_STRUCT_DIRENT_D_INO],[],[autoheader-fix])
AC_DEFINE([HAVE_USG_SIGHOLD],[],[autoheader-fix])
AC_DEFINE([HAVE_WCRTOMB],[],[autoheader-fix])
AC_DEFINE([HAVE_WCSCOLL],[],[autoheader-fix])
AC_DEFINE([HAVE_WCSDUP],[],[autoheader-fix])
AC_DEFINE([HAVE_WCTYPE],[],[autoheader-fix])
AC_DEFINE([HAVE_WCWIDTH],[],[autoheader-fix])
AC_DEFINE([MUST_REINSTALL_SIGHANDLERS],[],[autoheader-fix])
AC_DEFINE([NO_MULTIBYTE_SUPPORT],[],[autoheader-fix])
AC_DEFINE([SPEED_T_IN_SYS_TYPES],[],[autoheader-fix])
AC_DEFINE([STRCOLL_BROKEN],[],[autoheader-fix])
AC_DEFINE([STRUCT_WINSIZE_IN_SYS_IOCTL],[],[autoheader-fix])
AC_DEFINE([STRUCT_WINSIZE_IN_TERMIOS],[],[autoheader-fix])
AC_DEFINE([TIOCSTAT_IN_SYS_IOCTL],[],[autoheader-fix])
AC_DEFINE([VOID_SIGHANDLER],[],[autoheader-fix])
FIX
#
autoreconf -vifs
./configure CFLAGS="-fPIC $CFLAGS" --prefix=/usr
#
printf "RUN 'make SHLIB_LIBS=-lncurses' TO COMPILE\n"
#
exit $?
